### PR TITLE
Added sort_inter_class.py

### PR DESCRIPTION
**Pull request by sarimmehdi**
When you have lots of objects belonging to a different class, this will only run sort on objects of the same class. This can be combined with YOLO to track several different objects. What it essentially does is, in the IOU matrix, it assigns a value to 0 to any matched bounding boxes if the class of the two bounding boxes is different. 

So, for example, if the bounding box of the Person class matches that of the Bicycle class, the final IoU score will still be made 0 because both are two different classes. While, if the two bounding boxes are of the same class, this will not be done and the original IoU will be used as-is.

### CODE REVIEW

**Comment by haviduck** [comment]
hey man, great stuff. you added cid to the ret aswell, gonna scrap my patchy approach and use yours. cheers, owe you a beer.

**Comment by iAmJuan550** [comment]
@abewley if you feel this is ok then maybe you can commit it to your repo?

**Comment by sarimmehdi** [comment]
@haviduck I didn't encounter any range issues, can you do a test run and check if there is a problem?

**Comment by haviduck** [comment]
been so long and i dont have a vanilla setup to test. my current code throws index errors, but i csn look into it

**Comment by sarimmehdi** [comment]
@abewley @sodabeta7 if there are no issues with this commit, can you please add it to the repo? Thanks

**Pull request closed without merging**
